Bug/interactive window docker build
vshn/owasp-modsecurity-crs pull request #2
Opened 2020-09-30 08:55 UTC by ZuGao

Fixed the issue regarding interactive window popup during docker image build.

2020-09-30 16:19 UTC, bittner commented on util/docker/Dockerfile
> +  apt-get -y upgrade && \
Why does that fix the issue? Do you have a reference for that?

2020-10-01 14:17 UTC, ZuGao commented on util/docker/Dockerfile
> +  apt-get -y upgrade && \
I tested the building, unfortunately with just `apt-get -y update` doesn't work

2020-10-01 14:29 UTC, bittner requested changes

2020-10-01 14:29 UTC, bittner commented on util/docker/Dockerfile
> +  apt-get -y upgrade && \
I don't see `DEBIAN_FRONTEND=noninteractive` in any of the `RUN` blocks. This is the usual approach to avoid interactivity-based interruptions. I believe this would be the proper approach to fix this issue.

2020-10-01 14:40 UTC, ZuGao commented on util/docker/Dockerfile
> +  apt-get -y upgrade && \
Updated

2020-10-02 06:53 UTC, ZuGao commented on util/docker/Dockerfile
> +RUN export DEBIAN_FRONTEND=noninteractive && \
Updated the code again. I also thing upgrading the packages is a good idea.

2020-10-05 21:30 UTC, bittner approved these changes

2020-10-05 21:31 UTC, merged